.custom -*- mode: org -*-

;; Project: organize emacs dots in org. Right now I just want
;; to parallel the dots and rearrange. Later, org-babel to actually
;; replace em.

* Get Rid of Annoyances
(setq inhibit-startup-echo-area-message t)
(setq inhibit-startup-message t)
(fset 'yes-or-no-p 'y-or-n-p)
(setq visible-bell t)
;;Kill the excess newbie crap
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
;disable backup
(setq backup-inhibited t)
;disable auto save
(setq auto-save-default nil)
;Jump mouse out of the way
(mouse-avoidance-mode 'jump)
;;Highlight regions
(transient-mark-mode 1)
;Force files to end with newlines
(setq require-final-newline t)
;;show matching parens
(show-paren-mode 1)
(add-hook 'org-mode-hook 'turn-on-font-lock)  ; Org buffers only
(add-hook 'text-mode-hook 'turn-on-auto-fill)

; Wrap long lines according to the width of the window
(add-hook 'window-configuration-change-hook
          '(lambda ()
             (setq rcirc-fill-column (- (window-width) 2))))

(setq org-log-done t)

* Evil Mode
(evil-mode t)
(setq evil-normal-state-tag "NORMAL")
(setq evil-insert-state-tag "INSERT")
(setq evil-visual-state-tag "VISUAL")

* Font
(set-frame-font "Droid Sans Mono 13")

* Helm 
(setq helm-split-window-in-side-p t) ; open helm buffer inside current window, not occupy whole other window
 
* Theme
(require 'color-theme)
(color-theme-initialize)
(color-theme-subtle-hacker)

* Powerline
(powerline-evil-center-color-theme)

* Slime
(require 'slime-autoloads)
(load (expand-file-name "~/quicklisp/slime-helper.el"))
(require 'slime)
(setq inferior-lisp-program "/home/pook/ccl/lx86cl64")
(slime-setup)
; Ok, I've bashed my head against this for 3 cigarettes, and no dice.
; sbcl doesn't want to work with slime, even using quicklisp.
; Clisp, of course, works perfectly. 

